language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

# install codecov
before_install:
  - pip install codecov

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - coverage run tests.py

after_success:
  - codecov